import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/primaries/header/Header'
import Footer from '@/components/primaries/footer/Footer'







// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import SideBar from '@/components/primaries/user-panel/SideBar'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ممبرلند',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SideBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
